#!/bin/sh /etc/rc.common
# mu300-ufi:自建的 UFI-TOOLS 兼容后台(前端 /www/ufi + 后端 /www/ufi/api)
#   用第二个 uhttpd 实例跑在 2333,不动 LuCI 的 80 端口 ✓
START=95
STOP=10
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/uhttpd -f -h /www/ufi -x /api -p 0.0.0.0:2333
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}